import numpy as np
# import timeit

arr = np.random.random(100)
# t = timeit.timeit("np.sum(arr)", globals=globals(), number=100000)
# t2 = timeit.timeit("sum(arr)", globals=globals(), number=100000)
# print(t)
# print(t2)
# np.random.seed(0)
# arr = np.random.randint(15, size = (3,6))
# arr = np.arange(5)
# other_arr = np.ones((2,5))
# print(f"{arr} + {other_arr} = {arr + other_arr}")
# print(arr[1:, 2])
# print(np.reshape(arr, (2,9)))
# print(arr.transpose())
# print(np.hstack((arr, [[19],[29],[39]])))
# print(np.split(arr, [1,3], axis=0))

# arr = np.linspace(2,10, 5, dtype=np.int64)
# print(arr)
# print(np.where(arr > 4))
# print(type(arr))
# print(np.sum(arr))
# print(arr.ndim)
# print(arr.size)
# print(arr.dtype)

# arr = np.zeros((3,5), dtype=np.int64)
# print(arr)

# arr = np.arange(0,5,2)
# print(arr)
# newarr = np.random.random(7)
# print(newarr)
# arr = np.full((2,6),5)
# print(arr)
# rand_arr = np.random.randint(2,10,(2,3))
# print(rand_arr)